# Build and install Polybar
- name: 'Refresh facts'
  gather_facts:

- name: "Collecting installed packages"
  package_facts:
    manager: "apt"

- name: "Checking polybar installation status."
  shell: dpkg-query --showformat='dpkg --compare-versions "${Version}" "ge" "{{ debuild_polybar.git_branch }}"' -W polybar | sh
  register: polybar_status
  ignore_errors: true
  when: "'polybar' in ansible_facts.packages"
  changed_when: false

- name: 'Building polybar.'
  import_tasks: polybar.yml
  environment:
    GITREV: '{{ debuild_polybar.git_branch }}'
    GIT_URL: '{{ debuild_polybar.git_src }}'
  when: "'polybar' not in ansible_facts.packages or polybar_status.rc != 0"
  changed_when: false
